[tool.poetry]
name = "shaarpec"
version = "1.0.1"
description = "Client for SHAARPEC Analytics API."
authors = ["Erik G. Brandt <erik.brandt@shaarpec.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.23.0"
oidcish = "0.1.3"
anybadge = "^1.14.0"
anyio = "^3.6.2"
argon2-cffi = "^21.3.0"
argon2-cffi-bindings = "^21.2.0"
asttokens = "^2.0.8"
attrs = "^22.1.0"
Babel = "^2.10.3"
backcall = "^0.2.0"
background = "^0.2.1"
beautifulsoup4 = "^4.11.1"
black = "^22.10.0"
bleach = "^5.0.1"
certifi = "^2022.9.24"
cffi = "^1.15.1"
charset-normalizer = "^2.1.1"
click = "^8.1.3"
debugpy = "^1.6.3"
decorator = "^5.1.1"
defusedxml = "^0.7.1"
dill = "^0.3.5.1"
ecdsa = "^0.18.0"
entrypoints = "^0.4"
executing = "^1.1.1"
fastjsonschema = "^2.16.2"


[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
pylint = "^2.15.4"
isort = "^5.10.1"
jupytext = "^1.14.1"
jupyterlab-code-formatter = "^1.5.3"
anybadge = "^1.14.0"
jupyterlab = "^3.4.8"
nbconvert = "^7.2.1"
poetryup = "^0.12.3"
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
