[tool.poetry]
name = "shaarpec"
version = "2.0.1"
description = "Client for SHAARPEC Analytics API."
authors = ["Erik G. Brandt <erik.brandt@shaarpec.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.23.3"
oidcish = "0.1.3"
anybadge = "^1.14.0"
anyio = "^3.6.2"
argon2-cffi = "^21.3.0"
argon2-cffi-bindings = "^21.2.0"
asttokens = "^2.2.1"
attrs = "^22.2.0"
Babel = "^2.11.0"
backcall = "^0.2.0"
background = "^0.2.1"
beautifulsoup4 = "^4.11.1"
black = "^22.12.0"
bleach = "^5.0.1"
certifi = "^2022.12.7"
cffi = "^1.15.1"
charset-normalizer = "^3.0.1"
click = "^8.1.3"
debugpy = "^1.6.4"
decorator = "^5.1.1"
defusedxml = "^0.7.1"
dill = "^0.3.6"
ecdsa = "^0.18.0"
entrypoints = "^0.4"
executing = "^1.2.0"
fastjsonschema = "^2.16.2"
pylint = "^2.15.9"
tqdm = "^4.64.1"


[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
pylint = "^2.15.9"
isort = "^5.11.4"
jupytext = "^1.14.4"
jupyterlab-code-formatter = "^1.5.3"
anybadge = "^1.14.0"
jupyterlab = "^3.5.2"
nbconvert = "^7.2.7"
poetryup = "^0.12.7"
pytest = "^7.2.0"
pandas = "^1.5.2"
numpy = "^1.24.1"
matplotlib = "^3.6.2"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
